rules:
  indentation:
    - 2
    - 
      size: 4

  hex-length:
    - 2
    - style: long

  space-before-colon:
    - 0

  shorthand-values:
    - 0

  mixin-name-format:
    - 0

  class-name-format:
    - 0
